---
- name: "Runtime | Install Ansible"
  apt:
    name: ansible
    state: present
  tags: [packages, ansible]

- name: "Runtime | Show Ansible version"
  command: ansible --version
  changed_when: false
  when: ansible_debug | default(false)
