version: "3.9"

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alert_rules.yml:/etc/prometheus/alert_rules.yml
    networks:
      - monitoring_net

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    restart: unless-stopped
    command:
      - "--config.file=/config/alertmanager.yml"
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager/alertmanager.yml:/config/alertmanager.yml:ro
      - ./alertmanager/templates:/etc/alertmanager/templates:ro
    networks:
      - monitoring_net

  grafana:
    build: ./grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - ./grafana/.env.secrets
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - monitoring_net

  ntfy:
    image: binwiederhier/ntfy:latest
    container_name: ntfy
    restart: unless-stopped
    command: serve
    ports:
      - "8085:80"
    volumes:
      - ntfy_cache:/var/cache/ntfy
      - ./ntfy/config:/etc/ntfy
    env_file:
      - .env
    networks:
      - monitoring_net
      - noti_net

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - "9000:9000"   # HTTP UI
      - "9443:9443"   # HTTPS UI
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - monitoring_net

networks:
  monitoring_net:
    driver: bridge
  noti_net:
    driver: bridge

volumes:
  prometheus_data: {}
  grafana_data: {}
  ntfy_cache: {}
  portainer_data: {}
