global:
  scrape_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

#  - job_name: 'ssh'
#    static_configs:
#      - targets: [ 'ssh-exporter:9312' ]

rule_files:
  - "alert_rules.yml"
