version: "3"
services:
  ntfy:
    image: binwiederhier/ntfy:latest
    container_name: ntfy
    command:
      - serve
    ports:
      - "8085:80"
    volumes:
      - /mnt/m2drive/docker/data_ntfy:/var/cache/ntfy
      - ./config:/etc/ntfy
    env_file:
      - .env
    restart: unless-stopped
