version: "3"
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - "9443:9443"
    volumes:
      - /mnt/m2drive/docker/data_portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
