version: "3"
services:
  rustdesk_hbbs:
    image: rustdesk/rustdesk-server:latest
    container_name: rustdesk_hbbs
    command: hbbs
    volumes:
      - ./data:/root
    network_mode: "host"
    depends_on:
      - rustdesk_hbbr
    restart: unless-stopped
  rustdesk_hbbr:
    image: rustdesk/rustdesk-server:latest
    container_name: rustdesk_hbbr
    command: hbbr
    volumes:
      - ./data:/root
    network_mode: "host"
    restart: unless-stopped
